### PR TITLE
Adding automation for Travis CI

### PR DESCRIPTION
**Pull request by wcarhart**

### CODE REVIEW

**Comment by wcarhart** [comment]
test comment

**Comment by wcarhart** [comment]
**Good news!** *The content of your PR passed validation!*<br><br>In a few minutes, you can find a staged demo of Soliloquy with your new addition [here](https://soliloquy-dev.herokuapp.com/). Please take a second to review the staged demo and confirm that everything is as expected.<br><br>Once your PR is merged, your content will automatically appear on Soliloquy. When that happens, you can view it live [here](https://www.soliloquy.dev).<br><br>Thank you for your contribution! 🎉<br><br>*This message is automated.*

**Comment by wcarhart** [comment]
**Good news!** *The content of your PR passed validation!*<br><br>In a few minutes, you can find a staged demo of Soliloquy with your new addition [here](https://soliloquy-dev.herokuapp.com/). Please take a second to review the staged demo and confirm that everything is as expected.<br><br>Once your PR is merged, your content will automatically appear on Soliloquy. When that happens, you can view it live [here](https://www.soliloquy.dev).<br><br>Thank you for your contribution! 🎉<br><br>*This message is automated 🤖*

**Comment by friendly-committer** [comment]
**Good news!** *The content of your PR passed validation!*<br><br>In a few minutes, you can find a staged demo of Soliloquy with your new addition [here](https://soliloquy-dev.herokuapp.com/). Please take a second to review the staged demo and confirm that everything is as expected.<br><br>Once your PR is merged, your content will automatically appear on Soliloquy. When that happens, you can view it live [here](https://www.soliloquy.dev).<br><br>Thank you for your contribution! 🎉<br><br>*This is an automated message 🤖*

**Comment by friendly-committer** [comment]
**Good news!** *The content of your PR passed validation!*<br><br>In a few minutes, you can find a staged demo of Soliloquy with your new addition [here](https://soliloquy-dev.herokuapp.com/). Please take a second to review the staged demo and confirm that everything is as expected.<br><br>Once your PR is merged, your content will automatically appear on Soliloquy. When that happens, you can view it live [here](https://www.soliloquy.dev).<br><br>Thank you for your contribution! 🎉

**Comment by friendly-committer** [comment]
**Good news!** *The content of your PR passed validation!*<br><br>In a few minutes, you can find a staged demo of Soliloquy with your new addition [here](https://soliloquy-dev.herokuapp.com/). Please take a second to review the staged demo and confirm that everything is as expected.<br><br>Once your PR is merged, your content will automatically appear on Soliloquy. When that happens, you can view it live [here](https://www.soliloquy.dev).<br><br>Thank you for your contribution! 🎉

**Pull request merged**
